$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: Train Model
type: command

inputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  criterion:
    type: string
    default: squared_error
  max_depth:
    type: integer
    default: 5

outputs:
  model_output:
    type: mlflow_model

code: ../scripts
command: >-
  python model_train.py 
  --train_data ${{inputs.train_data}} 
  --test_data ${{inputs.test_data}} 
  --criterion ${{inputs.criterion}} 
  --max_depth ${{inputs.max_depth}} 
  --model_output ${{outputs.model_output}}

environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu:1 # <--- FIX: Updated environment
